services:
  backend_service:
    build: .
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - postgres_service

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=drf_commerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5434:5432"
