services:
  backend_service:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=drf_commerce      # ❗ baza nomi qo‘shildi
      - POSTGRES_USER=postgres        # ❗ foydalanuvchi nomi kiritildi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: